# Example configuration file for `monitor-stats`

process_blacklist = [
  "\\brg\\b.+--follow",
  "\\brsync\\b",
  "\\bcp\\b",
  "\\bmv\\b",
]

process_whitelist = ["^srun"]

# Listen with `while true;do nc -lN localhost 12345;echo;done`
[slack]
webhook_url = "http://localhost:8080"
