# Example configuration file for `monitor-stats`

# Listen with `while true;do nc -lN localhost 12345;echo;done`
slack_webhooks = ["http://localhost:12345"]

process_blacklist = [
    "\\brg\\b.+--follow",
    "\\brsync\\b",
    "\\bcp\\b",
    "\\bmv\\b",
]

process_whitelist = ["^srun"]
