FROM debian:12.10-slim

RUN apt-get update \
    && apt-get install -y libgd-dev cpanminus build-essential unzip \
    && cpanm GD::Graph \
    && apt-get autoremove -y --purge build-essential \
    && rm -rf /var/cache/apt/

RUN mkdir -p /maps /scratch \
    && ln -s /maps/projects /projects \
    && ln -s /maps/datasets /datasets

ADD https://www.chg.ox.ac.uk/~wrayner/tools/ic.v1.0.9.zip /usr/local/share/
RUN cd /usr/local/share/ \
    && unzip ic.v1.0.9.zip

ENTRYPOINT ["perl", "/usr/local/share/IC/ic.pl"]
